spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/usuarios
    username: user-service
    password: 123456
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      mode: never
server:
  port: 9997

jwt:
  secret: super-secret