spring:
  application:
    name: nota-fiscal-worker
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 5000
          multiplier: 2.0
          #max-interval: 10000
app:
  myport: ${PORT:0}
server:
  port: ${app.myport}

