apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cervejas
  name: {{.Release.Name}}-deploy
  labels:
    kube-monkey/enabled: enabled
    kube-monkey/identifier: monkey-victim
    kube-monkey/mtbf: '2'
    kube-monkey/kill-mode: "fixed"
    kube-monkey/kill-value: '1'
spec:
  replicas: 1
  selector:
    matchLabels:
      {{.Values.pod.label}}: {{.Values.pod.value}}
  template:
    metadata:
      name: {{.Release.Name}}-pod
      namespace: {{.Values.namespace}}
      labels:
        {{.Values.pod.label}}: {{.Values.pod.value}}
        kube-monkey/enabled: "enabled"
        kube-monkey/identifier: "monkey-victim"
        kube-monkey/mtbf: '2'
        kube-monkey/kill-mode: "fixed"
        kube-monkey/kill-value: '2'
    spec:
      containers:
        - name: {{.Release.Name}}-container
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
