apiVersion: v1
kind: Service
metadata:
  name: cerveja-service
  namespace: cervejas
spec:
  type: ClusterIP
  selector:
    service: cerveja
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP