apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: cervejas
spec:
  selector:
    service: gateway
  type: NodePort
  ports:
    - port: 9999
      targetPort: 9999
      nodePort: 31000