apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-express-service
  namespace: {{.Values.namespace}}
spec:
  type: NodePort
  selector:
    {{.Values.pod.label}}: {{.Values.pod.value}}
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30080
      protocol: TCP

