apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}-service
  namespace: {{.Values.namespace}}
spec:
  type: ClusterIP
  selector:
    {{.Values.pod.label}}: {{.Values.pod.value}}
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP

