server:
  port: 8080
spring:
  application:
    name: nota-fiscal-service
  main:
    allow-bean-definition-overriding: true
  dasource:
    url: jdbc:postgresql://POSTGRES-NOTAFISCAL:5432/postgres
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: RABBITMQ
    port: 5672
    username: cervejaria
    senha: 123456
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://EUREKA-SERVER:8761/eureka