apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-configmap
  namespace: {{.Values.namespace}}
data:
  {{- range $key,$value := .Values.configMapData}}
  {{$key}}: {{$value|quote}}
  {{- end}}
