apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{.Values.namespace}}
  name: {{.Release.Name}}-deploy
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      {{.Values.pod.label}}: {{.Values.pod.value}}
  template:
    metadata:
      name: {{.Release.Name}}-pod
      namespace: {{.Values.namespace}}
      labels:
        {{.Values.pod.label}}: {{.Values.pod.value}}
    spec:
      containers:
        - name: {{.Release.Name}}-container
          image: {{.Values.image.repository}}:{{.Values.image.tag}}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{.Release.Name}}-configmap
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5

