version: '3'
services:
  mongo:
    container_name: PEDIDO-MONGO-SERVER
    image: mongo:7-jammy
    volumes:
      - ./mongodb-data:/data/db
    networks:
      - cervejas
  # acesso administrativo MongoDB:
  #   http://0.0.0.0:8081 user: admin senha: pass
  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    links:
      - mongo
    container_name: "mongo-express"
    ports:
      - 8090:8081
    networks:
      - cervejas
networks:
  cervejas:
    external: true